@echo off
TITLE Hail from Unimatrix 01
SET /A borgNumber=%RANDOM%
cls
echo Beginning long-range scan...
set /p=Hit enter to continue...
cls
echo Anomalous reading detected. Analysing...
set /p=Hit enter to continue...
cls
echo Readings indicate presence of Particle 010
set /p=Hit enter to continue...
cls
echo Particle designation Omega
set /p=Hit enter to continue...
cls
echo Borg Vessel %borgNumber%... Prepare a Harmonic Resonance Chamber and capture Particle 010
set /p=Hit enter to continue...
cls
echo Stabilise the particle at any cost...
set /p=Hit enter to continue...
cls
exit

