@Echo off
TITLE Hail from Unimatrix 01
cls
echo Particle 010. Containment: Successesful
set /p=Hit enter to continue...
cls
echo Head for transwarp conduit 01182-A and return to the Primary Unimatrix.
set /p=Hit enter to continue...
cls
echo Begin repairs in sectors 0293,1204,14093,20123...
set /p=Hit enter to continue...
cls
exit
