@echo off
TITLE Hail from UNKNOWN, Cardassia Prime
cls
echo One of our scouts has data indicating the existence of an Omega Particle in the alpha quadrant.
set /p=Hit enter to continue...
cls
echo The Obsidian Order commands you to seize control of the particle before anyone else can get their hands on it.
set /p=Hit enter to continue...
cls
echo If our enemies get there before we do, they will destory Cardassia Prime. This cannot be allowed to happen.
set /p=Hit enter to continue...
cls
echo The future of Cardassia rests on your shoulders...
set /p=Hit enter to continue...
exit
