@echo off
Hail from UNKNOWN, Cardassia Prime
cls
echo You failed in your mission.
set /p=Hit enter to continue...
cls
echo You failed to save Cardassia Prime.
set /p=Hit enter to continue...
cls
echo You failed to save your family.
set /p=Hit enter to continue...
cls
echo You will certainly be demoted for this.
set /p=Hit enter to continue...
cls
echo Your new position is Janitor.
set /p=Hit enter to continue...
cls
echo You will be remembered as a Janitor.
set /p=Hit enter to continue...
cls
echo From Captain to Janitor
set /p=Hit enter to continue...
cls
echo How the mighty have fallen...
set /p=Hit enter to continue...
cls
exit
