@echo off
TITLE Hail from Weyoun, Omerian Nebula
cls
echo One of our moles in the Federation has told us of an Omega Particle forming in the alpha quadrant.
set /p=Hit enter to continue...
cls
echo The Founders, in all their wisdom, wish for you to acquire the particle.
set /p=Hit enter to continue...
cls
echo You must succeed, or the war in the alpha quadrant will be lost if our enemies weaponise the Omega.
set /p=Hit enter to continue...
cls
echo Glory to the Founders, do not fail...
set /p=Hit enter to continue...
cls
exit
