@echo off
TITLE Hail from Senator Vreenak, Romulus
cls
echo One of our warbirds has detected the formation of an Omega Particle in the alpha quadrant.
set /p=Hit enter to continue...
cls
echo The warbird was destroyed whilst tryin gto contain it, so you must seize it before the Federation and the Klingons.
set /p=Hit enter to continue...
cls
echo Your warbird will be refitted with Tal Shiar technology to aid your task.
set /p=Hit enter to continue...
cls
echo Do not fail...
set /p=Hit enter to continue...
cls
exit
